/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CrudFormWhereInput } from "./CrudFormWhereInput";
import { Type } from "class-transformer";
import { CrudFormOrderByInput } from "./CrudFormOrderByInput";

@ArgsType()
class CrudFormFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => CrudFormWhereInput,
  })
  @Field(() => CrudFormWhereInput, { nullable: true })
  @Type(() => CrudFormWhereInput)
  where?: CrudFormWhereInput;

  @ApiProperty({
    required: false,
    type: CrudFormOrderByInput,
  })
  @Field(() => CrudFormOrderByInput, { nullable: true })
  @Type(() => CrudFormOrderByInput)
  orderBy?: CrudFormOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { CrudFormFindManyArgs };
