/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumCrudFormRole } from "./EnumCrudFormRole";
import { IsEnum, IsOptional, ValidateNested } from "class-validator";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { Type } from "class-transformer";
@InputType()
class CrudFormUpdateInput {
  @ApiProperty({
    required: false,
    enum: EnumCrudFormRole,
  })
  @IsEnum(EnumCrudFormRole)
  @IsOptional()
  @Field(() => EnumCrudFormRole, {
    nullable: true,
  })
  role?: "Admin" | "Employee" | "Manager" | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}
export { CrudFormUpdateInput };
